// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JsonDerializer
{

    public class Guestcredential
    {
        public string username;
        public string password;
    }

}
