// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JsonDerializer
{

    public class JsonDerialize
    {
        public string schema;
        public string contentVersion;
        public Parameters parameters;
        public Variables variables;
        public Resource[] resources;
    }

}
