// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JsonDerializer
{

    public class Network
    {
        public string networkname;
        public string ipassignment;
        public string ipaddress;
        public string subnetmask;
        public string defaultgateway;
        public string[] dnsserver;
    }

}
