// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JsonDerializer
{

    public class Properties
    {
        public string description;
        public string vcenterserver;
        public string datacenter;
        public string cluster;
        public string vmhost;
        public string environment;
        public string template;
        public string Customizationspecs;
        public bool poweronaftercreation;
        public bool rebootforEdit;
        public bool enableCPUHotAdd;
        public bool enableMemoryHotAdd;
        public int vcpu;
        public int memoryinGB;
        public int corespersocket;
        public string datastore;
        public Network[] networks;
        public Disk[] disks;
        public Vcentercredential vcentercredential;
        public Guestcredential guestcredential;
        public Dscpullserver dscpullserver;
    }

}
