// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json.Linq;

namespace JsonDerializer
{

    public class Resource
    {
        public string type;
        public string name;
        public string dependsOn;
        public string mode;
        public Properties properties;
    }

}
